# JVM: memoria para Room/KSP sin morir en CI
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX (OBLIGATORIO: las librerias androidx no compilan sin esto)
android.useAndroidX=true
android.enableJetifier=false

# Kotlin code style
kotlin.code.style=official
